name: Palm
options:
  bundleIdPrefix: art.palm
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

targets:
  Palm:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: art.palm.daw
        PRODUCT_NAME: Palm
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        SWIFT_STRICT_CONCURRENCY: minimal
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_BITCODE: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_ENTITLEMENTS: ""
